# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170423_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='file_type',
        ),
        migrations.AddField(
            model_name='songs',
            name='song',
            field=models.FileField(default=datetime.datetime(2017, 4, 23, 20, 37, 35, 844144, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
