# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170424_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='song',
        ),
        migrations.AddField(
            model_name='songs',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
