# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 06:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20170424_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='is_favourite',
            new_name='is_favorite',
        ),
    ]
