# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_album_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='acces',
            field=models.CharField(default='public', max_length=250),
        ),
    ]
