# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20170424_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default='http://www.tubefilter.com/wp-content/uploads/2016/06/youtube-music-logo.jpg', max_length=1000),
        ),
    ]
